#!/bin/bash

#Options for the transcriptomics app
#
#c = "choose a course or module" (Mandatory drop down menu)
#    - Introduction to bulkRNAseq analysis (COURSE="Intro_to_bulkRNAseq")
#    - Single Cell RNA Seq data visualizer (COURSE="Cirrocumulus")
#
#f = Folder containing Single Cell RNA Seq datasets to be visualized in Cirrocumulus (.h5ad, .h5Seurat, .loom,  .zarr, TileDB data files, STAR-fusion table .tsv,). (Mandatory browsing box to choose a folder, only for the Cirrocumulus app)
#    - (CIRRO_FOLDER=$CHOSEN_FOLDER_IN_THE_MENU)

while getopts c:f: option
do
    case "${option}"
    in
        c) COURSE=${OPTARG};;
        f) CIRRO_FOLDER=${OPTARG};; #only for cirrocumulus choice of module
        \?) ## Invalid option
            printf "Error: invalid option.\n\n"
            exit;;
    esac
done

printf  "\n==================  "
printf  "\n Selecting Module  \n"
printf  "==================  \n\n"

# Intro to Single Cell RNAseq analysis with python
#if [ "${COURSE}" == "Intro_to_NGS" ]
#then
#    echo "-----> Chosen course: Introduction to NGS data"
#    if [ ! -d "Intro_to_NGS" ];
#    then
#        echo "-----> Linking fresh course material."
#        ln -s /usr/Intro_to_NGS /work/Intro_to_NGS
#    else
#        echo "-----> Using your own course material."
#    fi

    ### install kernels - this goes into start-jupyter
#    echo "-----> Installing course kernels on jupyterlab"
#    "${CONDA_DIR}"/envs/NGS_aarhus_py/bin/python -m ipykernel install --user --name="NGS_python" --display-name "NGS (Python)" && \
#    "${CONDA_DIR}"/envs/NGS_aarhus_r/bin/R -e "IRkernel::installspec(user=TRUE, name = 'NGS_R', displayname = 'NGS (R)')"

    ### modify kernel files with system variables
#    cp /usr/Intro_to_NGS/Environments/kernel_py_docker.json ~/.local/share/jupyter/kernels/ngs_python/kernel.json && \
#    cp /usr/Intro_to_NGS/Environments/kernel_R_docker.json ~/.local/share/jupyter/kernels/ngs_r/kernel.json

#    printf  "\n==================  "
#    printf  "\n Start JupyterLab  \n"
#    printf  "==================  \n\n"
    #add course name as variable to be used
#    bash -c "COURSE=${COURSE} jupyter lab --port=8787 --NotebookApp.token='' "
    
# Intro to single cell RNAseq with Rstudio
#elif [ "${COURSE}" == "Intro_to_bulkRNAseq" ]
#then
#    echo "-----> Chosen course: Introduction to bulk RNAseq analysis"
#    if [ ! -d "Intro_to_bulkRNAseq" ];
#    then
#        echo "-----> Linking fresh course material."
#        ln -s /usr/Intro_to_bulkRNAseq /work/Intro_to_bulkRNAseq
#    else
#        echo "-----> Using your own course material."
#    fi

#    printf  "\n===================  "
#    printf  "\n== Start RStudio ==  \n"
#    printf  "=================== \n\n"

#    sudo /init

# Start cirrocumulus    
if [ "${COURSE}" == "Cirrocumulus" ]
then
    echo "-----> Chosen module: Cirrocumuls - Single cell data explorer"
    echo "-----> Cirrocumulus data folder ${CIRRO_FOLDER}"

    printf  "\n===================  "
    printf  "\n== Start Cirrocumulus ==  \n"
    printf  "=================== \n\n"

    sudo chmod -R u=rwx,g=rwx ${CIRRO_FOLDER}/
    cd ${CIRRO_FOLDER}
    cirro launch --host 0.0.0.0 --port 8787 `ls -d ./` 

elif [ "${COURSE}" == "Intro_to_bulkRNAseq" ]
then
    echo "-----> Chosen course: Introduction to bulk RNAseq analysis"
    if [ ! -d "Intro_to_bulk" ];
    then
        echo "-----> Linking fresh course material."
        ln -s /usr/Intro_to_bulkRNAseq /work/Intro_to_bulkRNAseq
    else
        echo "-----> Using your own course material."
    fi

    printf  "\n===================  "
    printf  "\n== Start RStudio ==  \n"
    printf  "=================== \n\n"

    sudo /init
    
fi
