channels:
    - bioconda
    - r
    - conda-forge
    - plotly
    - pwwang
    - gwforg
    - maximinio
dependencies:
    - anndata
    - bedtools
    - bioconductor-airway
    - bioconductor-annotationhub
    - bioconductor-apeglm
    - bioconductor-batchelor
    - bioconductor-clusterexperiment
    - bioconductor-clusterprofiler
    - bioconductor-degreport
    - bioconductor-deseq2
    - bioconductor-dose
    - bioconductor-ensembldb
    - bioconductor-geneoverlap
    - bioconductor-genomeinfodb
    - bioconductor-ggtree
    - bioconductor-limma
    - bioconductor-loomexperiment
    - bioconductor-mast
    - bioconductor-multtest
    - bioconductor-pathview
    - bioconductor-rhdf5
    - bioconductor-singlecellexperiment
    - bioconductor-slingshot
    - bioconductor-tximport
    - bioconductor-vsn
    - bowtie2
    - eggnog-mapper
    - fastp
    - fastqc
    - gatk4
    - glpk
    - graphviz
    - hisat2
    - interproscan
    - ipykernel
    - jupyterlab
    - kallisto
    - loompy
    - markdown
    - multiqc
    - nextflow
    - qualimap
    - r-annotables
    - r-cluster
    - r-clustersim
    - r-cowplot
    - r-dofuture
    - r-factoextra
    - r-factominer
    - r-fossil
    - r-fpc
    - r-ggbeeswarm
    - r-ggnewscale
    - r-ggpubr
    - r-ggrepel
    - r-ggsci
    - r-globals>=0.16.1
    - r-parallelly>=1.34.0
    - r-gprofiler2
    - r-hexbin
    - r-httr
    - r-igraph
    - r-irkernel
    - r-matrix>=1.6_5
    - r-metap
    - r-nmf
    - r-patchwork
    - r-pheatmap
    - r-qlcmatrix
    - r-r.utils
    - r-rcolorbrewer
    - r-readxl
    - r-remotes
    - r-reticulate>=1.35
    - r-rfast
    - r-sceasy
    - r-sctransform
    - r-seurat=4.4.0
    - r-seuratwrappers
    - r-signac
    - r-statmod
    - r-stringi
    - r-tidyr
    - r-tidyverse
    - r-wgcna
    - rsem
    - rseqc
    - salmon
    - sambamba
    - samtools
    - scanpy
    - scrublet
    - slurm
    - snakemake
    - sortmerna
    - star
    - stringtie
    - subread
    - trimmomatic
