channels:
    - bioconda
    - r
    - conda-forge
    - plotly
dependencies:
    - conda-forge::plotly
    - conda-forge::jupyter-dash
    - conda-forge::ipywidgets
    - markdown
    - r-tidyverse
    - r-rcolorbrewer
    - r-pheatmap
    - r-cowplot
    - r-patchwork
    - r-r.utils
    - r-ggbeeswarm
    - r-factoextra
    - r-factominer
    - r-nmf
    - r-hexbin
    - r-statmod
    - r-ggpubr
    - r-ggsci
    - r-signac
    - r-metap
    - snakemake ###bulk RNA packages part 2
    - fastqc
    - multiqc
    - sortmerna
    - fastp
    - trimmomatic
    - star
    - hisat2
    - kallisto
    - bowtie2
    - salmon
    - subread
    - rsem
    - samtools
    - sambamba
    - bedtools
    - stringtie
    - interproscan
    - eggnog-mapper
    - qualimap
    - rseqc
    - gatk4
    - graphviz
    - r-irkernel ###scRNAseq packages
    - glpk
    - ipykernel
    - scanpy
    - r-tidyr
    - r-seurat=4.4.0
    - bioconductor-mast
    - bioconductor-multtest
    - r-metap
    - r-stringi
    - r-readxl
    - bioconductor-limma
    - r-remotes
    - r-wgcna
    - r-qlcmatrix
    - r-matrix=1.6_1
    - r-dofuture
    - scrublet
    - jupyterlab