channels:
    - bioconda
    - r
    - conda-forge
    - plotly
    - pwwang
    - gwforg
    - maximinio
dependencies:
    - anndata
    - bedtools
    - bioconductor-airway
    - bioconductor-annotationhub
    - bioconductor-apeglm
    - bioconductor-batchelor
    - bioconductor-clusterexperiment
    - bioconductor-clusterprofiler
    - bioconductor-degreport
    - bioconductor-deseq2
    - bioconductor-dose
    - bioconductor-ensembldb
    - bioconductor-geneoverlap
    - bioconductor-genomeinfodb
    - bioconductor-ggtree
    - bioconductor-limma
    - bioconductor-loomexperiment
    - bioconductor-mast
    - bioconductor-multtest
    - bioconductor-pathview
    - bioconductor-rhdf5
    - bioconductor-singlecellexperiment
    - bioconductor-slingshot
    - bioconductor-tximport
    - bioconductor-vsn
    - bowtie2
    - eggnog-mapper
    - fastp
    - fastqc
    - gatk4
    - glpk
    - graphviz
    - gxx_linux-64
    - hisat2
    - interproscan
    - ipykernel
    - jupyterlab
    - kallisto
    - loompy
    - markdown
    - multiqc
    - nextflow
    - qualimap
    - r-annotables
    - r-cluster
    - r-clustersim
    - r-cowplot
    - r-dofuture
    - r-factoextra
    - r-factominer
    - r-fossil
    - r-fpc
    - r-ggbeeswarm
    - r-ggnewscale
    - r-ggpubr
    - r-ggrepel
    - r-ggplot2=3.4.4
    - r-ggsci
    - r-globals>=0.16.1
    - r-parallelly>=1.34.0
    - r-gprofiler2
    - r-harmony>=1.0.1
    - r-hexbin
    - r-httr
    - r-igraph
    - r-irlba=2.3.5.1
    - r-irkernel
    - r-matrix=1.6_4
    - r-metap
    - r-nmf
    - r-patchwork=1.1.3
    - r-pheatmap
    - r-qlcmatrix
    - r-r.utils
    - r-rcolorbrewer
    - r-readxl
    - r-remotes
    - r-reticulate>=1.35
    - r-rfast
    - r-sceasy
    - r-sctransform
    - r-seurat=4.4.0
    - r-seuratwrappers
    - r-signac
    - r-statmod
    - r-stringi
    - r-tidyr
    - r-tidyverse
    - r-wgcna
    - rsem
    - rseqc
    - salmon
    - sambamba
    - samtools
    - scanpy
    - scrublet
    - slurm
    - snakemake
    - sortmerna
    - star
    - stringtie
    - subread
    - trimmomatic
    - pandas
    - numpy
    - matplotlib
    - jupyter_contrib_nbextensions # for auto-completion 
    - squidpy
    - pytest
    - pip:
      #### pip installations for spatial data tutorials
      # install method 1: latest pip release (recommended)
      - spatialdata
      - spatialdata-io
      - napari-spatialdata
      - spatialdata-plot
      #
      # install method 2: latest unreleased version (includes all latest bugfixes, but since it's not released code it may also introduce new bugs)
      # - git+https://github.com/scverse/spatialdata
      # - git+https://github.com/scverse/spatialdata-io
      # - git+https://github.com/scverse/napari-spatialdata
      # - git+https://github.com/scverse/spatialdata-plot
      #
      # install method 3: pinned release (guaranteed to work, does not include the latest bugfixes)
      # - spatialdata==0.2.3
      # - spatialdata-io==0.1.5
      # - napari-spatialdata==0.5.3
      # - spatialdata-plot==0.2.6
      #
      # install method 4: pinned unreleased version (not recommended, please use if the above does not work and you want unreleased bugfixes)
      # - git+https://github.com/scverse/spatialdata@a126e5804b8c982d9386703f6a108f8b078263a5
      # - git+https://github.com/scverse/spatialdata-io@6d20d76233cdc4d439dee7ec759f6420109de68f
      # - git+https://github.com/scverse/napari-spatialdata@a38e2866c9195866fecf1eca0f911d52587b163a
      # - git+https://github.com/scverse/spatialdata-plot@80c6f7774add354657a1e6b7fed28e162d614584
      #
      # additional packages
      - spatial-image==1.1.0
      - PyQt5 # for napari
      - lxml_html_clean # for napari
      - jupyter-black