#!/bin/bash

CIRRO_FOLDER=/usr/Cirrocumulus/Data/pbmc3k
PORT_USER=8787

## Options for the Transcriptomics Sandbox app
while getopts c:f:p: option; do
    case "${option}" in
    c) COURSE=${OPTARG} ;;
    f) CIRRO_FOLDER=${OPTARG} ;; # only for Cirrocumulus choice of module
    p) PORT_USER=${OPTARG} ;;
    \?)                          ## Invalid option
        printf "Error: invalid option.\n\n"
        exit
        ;;
    esac
done

printf "\n======================  "
printf "\n== Selecting Module == \n"
printf "======================  \n\n"

# RNAseq in Rstudio sandbox
if [ "${COURSE}" == "RNAseq_in_Rstudio" ]; then
    echo "-----> Chosen module: Rstudio"
    echo "with packages for RNAseq analysis"
    printf "\n===================  "
    printf "\n== Start RStudio ==  \n"
    printf "=================== \n\n"

    #!/bin/bash

    # Set the desired port
    PORT=${RSTUDIO_PORT:-$PORT_USER}
    # Update the RStudio Server configuration
    sudo echo "www-port=$PORT" >> /etc/rstudio/rserver.conf
    sudo /init 

# Cirrocumulus scRNA visualizer
elif [ "${COURSE}" == "Cirrocumulus" ]; then
    echo "-----> Chosen module: Cirrocumulus - Single cell data explorer"
    echo "-----> Cirrocumulus data folder ${CIRRO_FOLDER}"

    printf "\n========================  "
    printf "\n== Start Cirrocumulus ==  \n"
    printf "======================== \n\n"

    cd "${CIRRO_FOLDER}"

    eval "$(/opt/miniconda/bin/conda shell.bash hook)" 
    conda activate /opt/miniconda/envs/RNAseq_env
    cirro launch --host 0.0.0.0 --port $PORT_USER ./*.h5ad

# Intro to bulk RNAseq with Rstudio
elif [ "${COURSE}" == "Intro_to_bulkRNAseq" ]; then
    echo "-----> Chosen course: Introduction to bulk RNAseq analysis in R"

    if [ ! -d "Notebooks" ]; then
        eval "$(/opt/miniconda/bin/conda shell.bash hook)" 
        conda activate /opt/miniconda/envs/RNAseq_env 

        echo "-----> Downloading fresh course material."
        #Clone the repo and move the notebooks, then remove
        git clone --depth 1 https://github.com/hds-sandbox/bulk_RNAseq_course.git /tmp/course
        mv /tmp/course/Notebooks  .
        mkdir -p Scripts
        mv /tmp/course/Scripts/ucloud_preprocessing_setup Scripts/
        rm -rf /tmp/course
        #Download only data and unzip
        zenodo_get 10.5281/zenodo.7116370 -w test.txt
        wget `grep Data test.txt`
        unzip Data.zip; rm Data.zip
        #make the results folder
        mkdir -p Results

        conda deactivate

    else
        echo "-----> Using your own course material."

    fi

    #bashrc file for conda
    echo 'eval "$(/opt/miniconda/bin/conda shell.bash hook)"'>>/home/ucloud/.bashrc   
    echo 'conda activate /opt/miniconda/envs/RNAseq_env'>>/home/ucloud/.bashrc

    # Set the desired port
    PORT=${RSTUDIO_PORT:-$PORT_USER}
    # Update the RStudio Server configuration
    sudo echo "www-port=$PORT" >> /etc/rstudio/rserver.conf
    sudo /init 

# Intro to spatial transcriptomics with scVerse
elif [ "${COURSE}" == "Intro_spatial_scverse" ]; then
    echo "-----> Chosen course: introduction to spatial transcriptomics"
    eval "$(/opt/miniconda/bin/conda shell.bash hook)" 
    conda activate /opt/miniconda/envs/RNAseq_env 

    if [ ! -d "Notebooks" ]; then

        echo "-----> Downloading fresh course material."
        #Clone the repo and move the notebooks, then remove
        git clone -b hds-sandbox-main --depth 1 https://github.com/hds-sandbox/workshop_intro_spatial_scverse.git /tmp/course
        mv /tmp/course/notebooks  ./Notebooks
        mkdir -p Resources Sandbox
        mv /tmp/course/resources Resources/
        mv /tmp/course/sandbox Sandbox/
        mv /tmp/course/download.py test_notebook.sh .
        rm -rf /tmp/course

    else
        echo "-----> Using your own course material."

    fi
    
    #bashrc file for conda
    echo 'eval "$(/opt/miniconda/bin/conda shell.bash hook)"'>>/home/ucloud/.bashrc   
    echo 'conda activate /opt/miniconda/envs/RNAseq_env'>>/home/ucloud/.bashrc

    #start a session of jupyterlab
    eval "$(/opt/miniconda/bin/conda shell.bash hook)" 
    conda activate /opt/miniconda/envs/RNAseq_env 
    /opt/miniconda/envs/RNAseq_env/bin/R -e "IRkernel::installspec(user=TRUE, name = 'r_scrna', displayname = 'R analysis')"
    SHELL=/bin/bash jupyter-lab --port=$PORT_USER --ip=0.0.0.0 --NotebookApp.token='' --no-browser


# Intro to scRNAseq with Rstudio
elif [ "${COURSE}" == "Intro_scRNAseq_R" ]; then
    echo "-----> Chosen course: Introduction to scRNAseq analysis in R"

    if [ ! -d "Notebooks" ]; then

        eval "$(/opt/miniconda/bin/conda shell.bash hook)" 
        conda activate /opt/miniconda/envs/RNAseq_env 

        echo "-----> Downloading fresh course material."
        #Clone the repo and move the notebooks, then remove
        git clone --depth 1 https://github.com/hds-sandbox/scRNASeq_course.git /tmp/course
        mv /tmp/course/Notebooks .
        rm -rf /tmp/course
        #Download only data and unzip
        zenodo_get 10.5281/zenodo.7827898 -w test.txt
        wget `grep Data test.txt`
        unzip Data.zip; rm Data.zip
        #make the results folder
        mkdir -p Results

        conda deactivate

    else
        echo "-----> Using your own course material."

    fi
    
    #bashrc file for conda
    echo 'eval "$(/opt/miniconda/bin/conda shell.bash hook)"'>>/home/ucloud/.bashrc   
    conda 'activate /opt/miniconda/envs/RNAseq_env'>>/home/ucloud/.bashrc
    #start a session of rstudio server
    printf "\n===================  "
    printf "\n== Start RStudio ==  \n"
    printf "=================== \n\n"

    # Set the desired port
    PORT=${RSTUDIO_PORT:-$PORT_USER}
    # Update the RStudio Server configuration
    sudo echo "www-port=$PORT" >> /etc/rstudio/rserver.conf
    sudo /init 

#RNAsequencing development on jupyterlab
elif [ "${COURSE}" == "RNAseq_CLI" ]; then
    echo "-----> Chosen environment: Jupyterlab for CLI,"
    echo "python and R RNAseq analysis"

    printf "\n========================  "
    printf "\n== Start RNAseq CLI ==  \n"
    printf "======================== \n\n"

    rm /home/$USER/.Rprofile
    eval "$(/opt/miniconda/bin/conda shell.bash hook)" 
    conda activate /opt/miniconda/envs/RNAseq_env 
    /opt/miniconda/envs/RNAseq_env/bin/R -e "IRkernel::installspec(user=TRUE, name = 'r_scrna', displayname = 'R analysis')"
    SHELL=/bin/bash jupyter-lab --port=$PORT_USER --ip=0.0.0.0 --NotebookApp.token='' --no-browser


#Advanced single cell transcriptomics
elif [ "${COURSE}" == "Advanced_SingleCell" ]; then
    echo "-----> Chosen environment: Advanced single cell analysis"

    if [ ! -d "AdvancedSingleCell" ]; then
        printf "\n-----> Downloading repository material\n"
        git clone --depth 1 https://github.com/hds-sandbox/AdvancedSingleCell.git AdvancedSingleCell
    fi

    printf "\n========================  "
    printf "\n===== Start Module =====  \n"
    printf "========================== \n\n"

    #bashrc file for conda
    echo 'eval "$(/opt/miniconda/bin/conda shell.bash hook)"'>>/home/ucloud/.bashrc   
    echo 'conda activate /opt/miniconda/envs/RNAseq_env'>>/home/ucloud/.bashrc

    eval "$(/opt/miniconda/bin/conda shell.bash hook)" 
    conda activate /opt/miniconda/envs/RNAseq_env 
    echo ".libPaths(c(\"/opt/miniconda/envs/RNAseq_env/lib/R/library/\"))" > /home/ucloud/.Rprofile
    /opt/miniconda/envs/RNAseq_env/bin/R -e "IRkernel::installspec(user=TRUE, name = 'r_scrna', displayname = 'R Adv Single Cell')"
    SHELL=/bin/bash jupyter-lab --port=$PORT_USER --ip=0.0.0.0 --NotebookApp.token='' --no-browser
fi
